[helpers]

[default]
depends = []

[default.files]
# Ghostty
"ghostty.conf" = "~/.config/ghostty/config"

# Yazi file manager
"yazi.toml" = "~/.config/yazi/yazi.toml"

# Cursor
"cursor/settings.json" = "~/.config/Cursor/User/settings.json"
"cursor/keybindings.json" = "~/.config/Cursor/User/keybindings.json"

# Antigravity
"antigravity/settings.json" = "~/.config/Antigravity/User/settings.json"
"antigravity/keybindings.json" = "~/.config/Antigravity/User/keybindings.json"

# Positron
"positron/settings.json" = "~/.config/Positron/User/settings.json"
"positron/keybindings.json" = "~/.config/Positron/User/keybindings.json"

# Arkenfox (Firefox hardenning)
"firefox/user-overrides.js" = "~/.mozilla/firefox/023rvj2f.default-release/user-overrides.js"

# Claude Code
"claude-code/CLAUDE.md" = "~/.config/claude-code/CLAUDE.md"
"claude-code/commands/" = "~/.config/claude-code/commands/"
"claude-code/statusline-command.sh" = "~/.config/claude-code/statusline-command.sh"

[default.variables]

[settings]
default_target_type = "automatic"
